spring:
  application:
    name: library-intec
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/library_intec
    driver-class-name: org.postgresql.Driver